# Generated by Django 4.2.7 on 2023-11-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='day_type',
            field=models.CharField(choices=[('toq', 'Toq'), ('juft', 'Juft')], default='toq', max_length=10),
        ),
    ]
